version: '3.1'

services:
  apidocker:
    image: manologcode/apidocker
    restart: always
    container_name: apidocker
    command: uvicorn main:app --port=5000 --host='0.0.0.0' --reload
    ports:
      - "8888:5000"
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock

